import "./globals.css";
import { Inter, Nunito } from "next/font/google";

import Navbar from "~/components/navbar/Navbar";
import ToasterProvider from "~/providers/ToasterProvider";

import LoginModal from "~/components/modals/LoginModal";
import RegisterModal from "~/components/modals/RegisterModal";

import { getCurrentUser } from "~/app/actions/getCurrentUser";

// const inter = Inter({ subsets: ['latin'] })
const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={nunito.className}>
        <ToasterProvider />

        <LoginModal />
        <RegisterModal />

        <Navbar user={currentUser} />

        <div className="pb-20 pt-28">{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
